# Generated by Django 3.1.2 on 2020-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public circles are listed in the main page so everyone know about their experiences'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='members_limit',
            field=models.PositiveIntegerField(default=0, help_text='If circle is limited, this will be the limit on the number of members.'),
        ),
    ]
